CREATE TABLE IF NOT EXISTS competition (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(160) NOT NULL,
    track VARCHAR(32) NOT NULL,
    organizer VARCHAR(160) NOT NULL,
    season VARCHAR(160) NOT NULL DEFAULT '',
    level_class VARCHAR(20) NOT NULL,
    scope VARCHAR(20) NOT NULL,
    tags TEXT NOT NULL,
    description TEXT NOT NULL,
    official_url VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    registration_deadline DATE NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_competition_name (name),
    KEY idx_competition_status_track (status, track),
    KEY idx_competition_deadline (registration_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO competition
    (name, track, organizer, season, level_class, scope, tags, description, official_url, status, created_at, updated_at)
VALUES
('中国国际大学生创新大赛（原“互联网+”）', 'innovation', '教育部等', '校赛约 4–6 月，国赛约 9–10 月', '一类A', '国赛', '["双创","路演","红旅"]', '覆盖高教主赛道、职教赛道、产业命题、青年红色筑梦之旅等，适合有项目沉淀的团队。', 'https://cy.ncss.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“挑战杯”全国大学生课外学术科技作品竞赛', 'innovation', '共青团中央等', '奇数年举办，校赛多在上半学年启动', '一类A', '国赛', '["大挑","学术","科技作品"]', '偏学术与科技创新作品展示，与“小挑”创业计划竞赛交替举办。', 'http://www.tiaozhanbei.net/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“挑战杯”中国大学生创业计划大赛', 'innovation', '共青团中央等', '偶数年举办', '一类A', '国赛', '["小挑","创业计划"]', '侧重创业计划与商业模式，适合早期创业项目打磨与路演。', 'http://www.tiaozhanbei.net/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生数学建模竞赛', 'stem', '中国工业与应用数学学会等', '每年 9 月（通常 3 天赛）', '一类B', '国赛', '["建模","论文","国赛"]', '连续三天封闭式建模与论文写作，考察问题抽象、模型与求解、论文表达。', 'http://www.mcm.edu.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('美国大学生数学建模竞赛（MCM/ICM）', 'stem', 'COMAP', '每年 1–2 月（寒假）', '三类', '国际赛', '["美赛","英文论文"]', '英文论文、选题开放，常与国赛备赛体系衔接。', 'https://www.contest.comap.com/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ACM-ICPC / CCPC 系列', 'cs', '各赛区 / 组委会', '区域赛多在秋季，校队选拔因校而异', '一类B', '国赛', '["算法","程序设计","组队"]', '5 小时现场编程，强调算法与团队协作，适合长期训练队伍。', 'https://icpc.global/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('蓝桥杯全国软件和信息技术专业人才大赛', 'cs', '工信部人才交流中心等', '省赛约 4 月，国赛约 6 月', '一类B', '国赛/省赛', '["软件类","单片机","嵌入式"]', '个人赛为主，覆盖软件开发、嵌入式、物联网等方向，门槛相对友好。', 'https://dasai.lanqiao.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国高校计算机大赛（含多个子赛）', 'cs', '教指委等', '因子赛而异，多集中在春夏', '一类B', '国赛', '["移动应用","网络技术","人工智能","大数据"]', '如移动应用创新赛、网络技术挑战赛、人工智能创意赛等，可按子赛选报。', 'https://www.c4best.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生电子设计竞赛', 'ee', '教育部、工信部', '奇数年国赛，暑期集中测评', '一类B', '国赛', '["模电","数电","作品"]', '四天三夜制作实物作品，强调电路设计与系统实现能力。', 'https://www.nuedc.com.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“西门子杯”中国智能制造挑战赛', 'ee', '教育部国际合作与交流司等', '校赛 / 省赛春夏，国赛暑假', '一类B', '国赛', '["自动化","PLC","工业网络"]', '面向自动化、机电、计算机等方向的工程实践类赛事。', 'http://www.siemenscup-cimc.org.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生智能汽车竞赛', 'robot', '教指委', '校赛春季起，分区赛与全国赛暑假', '一类B', '国赛', '["嵌入式","视觉","控制"]', '以智能车为载体，涵盖摄像头、电磁、创意组等多组别。', 'https://smartcar.cdstm.cn/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('RoboMaster 机甲大师赛', 'robot', '大疆等', '备赛周期长，分区赛与总决赛多在春夏', '一类B', '国赛', '["机器人","对抗","战队"]', '机器人对抗与工程能力并重，适合有实验室与经费支持的战队。', 'https://www.robomaster.com/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国机器人及人工智能大赛', 'robot', '中国人工智能学会等', '省赛与国赛多在夏季', '一类B', '国赛', '["机器人","人工智能"]', '赛项多、覆盖面广，含仿真与实物等多种形态。', 'https://www.caairobot.com/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“外研社·国才杯”理解当代中国系列赛事', 'general', '外研社等', '校赛秋季，国赛秋冬', '一类B', '国赛', '["英语","演讲","写作","阅读"]', '英语演讲、写作、阅读等分项，适合语言类能力提升与综测加分。', 'https://ucc.fltrp.com/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国大学生医学技术技能大赛', 'general', '教育部', '以当年组委会通知为准', '一类B', '国赛', '["医学","技能","临床"]', '医学类专业实践技能竞赛，强调临床操作与综合能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生机械创新设计大赛', 'general', '教育部高等学校机械学科教学指导委员会', '校赛至国赛，周期约半年至一年', '一类B', '国赛', '["机械","设计","创新"]', '面向机械类与工程类学生的实物创新设计竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生结构设计竞赛', 'general', '中国高等教育学会工程教育专业委员会等', '校赛春季，省赛/国赛夏秋', '一类B', '国赛', '["土木","结构","工程"]', '以模型结构设计与加载测试为核心，突出工程实践能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生广告艺术大赛', 'general', '教育部高等学校新闻传播学类专业教学指导委员会等', '每年赛季安排以官方通知为准', '一类B', '国赛', '["广告","创意","传播"]', '广告与视觉传播方向的全国性学生竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生电子商务“创新、创意及创业”挑战赛', 'innovation', '教育部高等学校电子商务专业教学指导委员会', '校赛春季，省赛/国赛夏季', '一类B', '国赛', '["电商","三创赛","创新创业"]', '聚焦电子商务领域项目方案、商业模式与路演能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国大学生工程实践与创新能力大赛', 'general', '教育部工程训练教学指导委员会', '校赛至国赛分阶段进行', '一类B', '国赛', '["工程训练","实践","创新"]', '强调工程训练、综合设计与团队协作。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生物流设计大赛', 'general', '教育部高等学校物流类专业教学指导委员会', '每届时间以赛事公告为准', '一类B', '国赛', '["物流","供应链","方案设计"]', '面向物流与供应链管理的实战型方案竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('两岸新锐设计竞赛·华灿奖', 'general', '中国高等教育学会', '年度赛', '一类B', '国赛', '["设计","文创","两岸"]', '聚焦视觉设计、产品设计、数字创意等方向。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生创新创业训练计划年会展示', 'innovation', '教育部高等教育司', '年度年会展示', '一类B', '国赛', '["大创","创新创业","项目展示"]', '国家级大学生创新创业训练计划项目集中展示交流活动。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生化工设计竞赛', 'general', '中国化工学会化学工程专业委员会等', '春夏组织校赛与区域赛', '一类B', '国赛', '["化工","流程设计","工程"]', '围绕化工流程与工艺设计的工程类竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生市场调查与分析大赛', 'general', '教育部高等学校统计学类专业教学指导委员会等', '每年春季启动', '一类B', '国赛', '["市调","统计","分析"]', '强调调研设计、数据分析与报告表达。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生先进成图技术与产品信息建模创新大赛', 'general', '教育部高等学校工程图学课程教学指导委员会等', '年度赛', '一类B', '国赛', '["成图","建模","BIM"]', '涵盖工程制图、三维建模与信息化表达能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国三维数字化创新设计大赛', 'general', '全国三维数字化创新设计大赛组委会等', '年度赛', '一类B', '国赛', '["3D","数字化","设计"]', '面向三维数字化设计、创意与应用实践。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国大学生服务外包创新创业大赛', 'innovation', '教育部、商务部等', '每年春夏组织', '一类B', '国赛', '["服务外包","创新创业","项目实践"]', '以企业真实需求为导向的创新实践赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国大学生计算机设计大赛', 'cs', '中国高等教育学会、教育部高等学校计算机类专业教学指导委员会等', '年度赛', '一类B', '国赛', '["计算机","设计","应用开发"]', '覆盖软件应用、数媒设计、人工智能等多个赛道。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生光电设计竞赛', 'ee', '中国光学学会等', '年度赛', '一类B', '国赛', '["光电","电子","工程"]', '聚焦光电系统设计与实现能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生集成电路创新创业大赛', 'ee', '工业和信息化部人才交流中心', '每年赛季以公告为准', '一类B', '国赛', '["集成电路","芯片","创新创业"]', '半导体与集成电路方向的重要学生赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生信息安全竞赛', 'cs', '教育部高等学校信息安全类专业教学指导委员会', '每年多阶段进行', '一类B', '国赛', '["网络安全","攻防","信息安全"]', '覆盖安全理论、实战攻防、应用创新等方向。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国大学生机械工程创新创意大赛', 'general', '中国机械工程学会', '年度赛', '一类B', '国赛', '["机械工程","创新创意","制造"]', '机械类综合创新创意竞赛，含多个专项赛道。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“中国软件杯”大学生软件设计大赛', 'cs', '工业和信息化部、教育部等', '年度赛', '一类B', '国赛', '["软件开发","工程实践","应用设计"]', '聚焦软件工程与应用创新开发能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“大唐杯”全国大学生新一代信息通信技术大赛', 'ee', '工业和信息化部人才交流中心、中国通信企业协会', '年度赛', '一类B', '国赛', '["通信","5G","ICT"]', '信息通信技术方向的全国大学生竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('华为 ICT 大赛', 'ee', '华为技术有限公司', '年度赛', '一类B', '国赛', '["华为","ICT","云与网络"]', '面向网络、云、计算、AI 等方向的技术竞赛。', 'https://e.huawei.com/cn/talent/ict-academy/ict-competition', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生嵌入式芯片与系统设计竞赛', 'ee', '中国电子学会', '年度赛', '一类B', '国赛', '["嵌入式","芯片","系统设计"]', '强调芯片应用、嵌入式系统与软硬件协同设计。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生生命科学竞赛（CULSC）', 'general', '教育部', '年度赛', '一类B', '国赛', '["生命科学","实验","研究"]', '生命科学方向的研究与创新实践竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生物理实验竞赛', 'stem', '教育部高等教育司', '年度赛', '一类B', '国赛', '["物理实验","实验技能","创新"]', '面向物理实验教学与创新实践能力提升。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国高校 BIM 毕业设计创新大赛', 'general', '中国土木工程学会建筑市场与招标投标研究分会等', '年度赛', '一类B', '国赛', '["BIM","土木","毕业设计"]', '建筑与土木工程方向的 BIM 应用竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国机器人及人工智能大赛', 'robot', '中国人工智能学会', '年度赛', '一类B', '国赛', '["机器人","人工智能","算法"]', '覆盖机器人、智能控制、视觉与 AI 应用等赛道。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生节能减排社会实践与科技竞赛', 'general', '教育部高等教育司、教育部高等学校能源动力学科教学指导委员会', '年度赛', '一类B', '国赛', '["节能减排","社会实践","科技"]', '鼓励能源与环保方向的创新实践项目。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“21 世纪杯”全国英语演讲比赛', 'general', '21 世纪报社', '年度赛', '一类B', '国赛', '["英语","演讲","表达"]', '全国性英语演讲赛事，注重语言表达与思辨能力。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('iCAN 大学生创新创业大赛', 'innovation', '国际 iCAN 联盟、教育部创新创业教育指导委员会等', '年度赛', '一类B', '国赛', '["iCAN","创新创业","项目孵化"]', '面向技术创新与创业实践的综合竞赛平台。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('“工行杯”全国大学生金融科技创新大赛', 'innovation', '中国工商银行股份有限公司', '年度赛', '一类B', '国赛', '["金融科技","FinTech","创新"]', '聚焦金融科技应用创新与行业场景实践。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏大学生创新大赛', 'innovation', '江苏省教育厅等', '省赛年度举办', '二类A', '省赛', '["江苏省赛","创新创业","项目路演"]', '江苏省重点大学生创新创业赛事，与国创类赛事衔接。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省师范生教学基本功大赛', 'general', '江苏省教育厅', '省赛年度举办', '二类A', '省赛', '["师范生","教学技能","江苏省赛"]', '师范生教学设计与课堂展示能力竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省大学生职业规划大赛', 'general', '江苏省教育厅', '省赛年度举办', '二类B', '省赛', '["职业规划","生涯发展","江苏省赛"]', '面向全省高校大学生的职业规划与发展能力赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省大学生程序设计大赛', 'cs', '江苏省计算机学会', '省赛年度举办', '二类B', '省赛', '["程序设计","算法","江苏省赛"]', '江苏省高校程序设计能力竞技赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省大学生网络空间安全知识技能大赛', 'cs', '江苏省计算机学会', '省赛年度举办', '二类B', '省赛', '["网络安全","攻防","江苏省赛"]', '网络安全方向省级技能竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省大学生电子设计竞赛', 'ee', '全国大学生电子设计竞赛江苏赛区组织委员会', '省赛年度举办', '二类B', '省赛', '["电子设计","硬件","江苏省赛"]', '电子系统设计与实现能力省级竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('江苏省高校智能机器人创意大赛', 'robot', '江苏省高校智能机器人创意大赛组委会', '省赛年度举办', '二类B', '省赛', '["机器人","创意","江苏省赛"]', '机器人创意设计与实现的省级赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国高校计算机能力挑战赛', 'cs', '全国高等学校计算机教育研究会', '年度赛', '二类B', '国赛', '["计算机","能力挑战","应用"]', '覆盖编程、算法与综合应用能力的竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('中国高校计算机大赛 AIGC 创新赛', 'cs', '全国高等学校计算机教育研究会', '年度赛', '一类B', '国赛', '["AIGC","人工智能","创新"]', '聚焦生成式 AI 与相关应用创新的专项赛事。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('全国大学生 GIS 应用技能大赛', 'general', '中国地理信息产业协会、中国地理学会', '年度赛', '二类B', '国赛', '["GIS","地理信息","应用技能"]', '地理信息系统应用开发与分析能力竞赛。', '', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('美国大学生数学建模竞赛（MCM）', 'stem', '美国工业与应用数学学会等', '每年寒假赛季', '三类', '国际赛', '["MCM","数学建模","英文论文"]', '国际知名数学建模赛事，强调建模与英文论文表达。', 'https://www.contest.comap.com/', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
